### ISSUE TITLE
Messages get deleted on reconnection

### ISSUE THREAD

**Issue by seffs** [FKLC/WhatsAppToDiscord#22] opened 2020-12-04 10:43 UTC
Hi there, so I was playing around with your tool. I discovered that every time the session times out, all chats are gone. Is that intended behaviour? Or is my bot missing some permissions?

**Comment by Hyper-Smartian** [comment] 2020-12-09 09:01
It is sent through discord channels, so check the audit log of the server if it gets deleted after it is displayed on the channel.

**Comment by seffs** [comment] 2020-12-10 05:14
Yes it does 
![image](https://user-images.githubusercontent.com/46768740/101724431-dd82f600-3aae-11eb-838d-cb4848382953.png)
I can't restrict its manage channels permission bc it wouldn't create the channels otherwise

**Comment by FKLC** [comment] 2020-12-10 05:19
When it times out what happens exactly? Does the bot shuts itself down or it reconnects automatically?

**Comment by seffs** [comment] 2020-12-10 05:30
It tries to reconnect and it does:

![image](https://user-images.githubusercontent.com/46768740/101725275-9eee3b00-3ab0-11eb-8bfe-60ea09b6b10d.png)

The channels get removed and everything starts from scratch. Today something completely different happened however. The channels started to appear duplicated. Plus when I try to invoke the list command this happens:

![image](https://user-images.githubusercontent.com/46768740/101725511-158b3880-3ab1-11eb-8c00-5094d50f3da9.png)

**Comment by FKLC** [comment] 2020-12-10 05:36
To be honest, since I cannot reproduce the bug it is hard for me to understand what is going on. Can you do me a favour and delete `chats.json`, `session.json` and all the channels under `WHATSAPP` category except `control-room`. I don't expect anything happening but it's like clearing cache, it might worth giving a shot.

**Comment by seffs** [comment] 2020-12-10 05:48
Ok, just did that and the `start` and `list` commands started working again. I will let it run for the rest of the day and report back if the issue persists

**Comment by teejavus** [comment] 2020-12-10 08:32
I'm facing the same issue, and tried this out.

> To be honest, since I cannot reproduce the bug it is hard for me to understand what is going on. Can you do me a favour and delete `chats.json`, `session.json` and all the channels under `WHATSAPP` category except `control-room` and then run it again. I don't expect anything happening but it's like clearing cache, it might worth giving a shot.

But I'm getting timed out and when I join, chats are still getting deleted. Also, `start` is failing for me.

**Comment by seffs** [comment] 2020-12-11 06:12
So just a couple of minutes ago it happened. All channels got deleted after reconnection. Commands are still working. Mind you, the bot's PID was never finished/killed, it just reconnected as normal. Since you mention `chats.json` and `session.json` , might it be related to the program never dumping those in the meantime? Both files are present after a fresh start

**Comment by seffs** [comment] 2020-12-11 06:51
After much debugging, I realized the culprit was me not understanding how Heroku and its Dynos work... Ofc, after the 24h span both files will get deleted, starting the program from point 0. 

Which leads me to the question: Is it possible to save to a DB instead of .json files? That would be a cool feature and helps data persistency all in all.

**Comment by teejavus** [comment] 2020-12-11 09:01
@seffs I just use it locally, don't see a point of running it constantly for the time being. 

@FKLC `error processing data: error decoding binary: could not decode binary: invalid string with tag 174` this happens when I start again after time out and deletes the old chats.

**Comment by FKLC** [comment] 2020-12-11 19:24
> @FKLC `error processing data: error decoding binary: could not decode binary: invalid string with tag 174` this happens when I start again after time out and deletes the old chats.

This is expected and not on my end. This error is produced by go-whatsapp and doesn't interfere with this scripts' flow. Start is probably failing because it matches with existing channels. However, this should not happen and that's literally why the `repairChannels()` function exists. It removes channels if it's not on the `chats.json` file or it removes channels from `chats.json` if the user decided to delete it. Since, I can't reproduce the bug I can't help you with this issue. Maybe check if program has permission to write files and also check if it has `Manage Channels` permission on Discord.

**Comment by teejavus** [comment] 2020-12-11 20:37
`It removes channels if it's not on the chats.json file or it removes channels from chats.json if the user decided to delete it.` 
@FKLC I feel this might be the issue - I just realised I dont see a chats.json for me, only session/settings.json

`Maybe check if program has permission to write files and also check if it has Manage Channels permission on Discord.`
Not sure how to check the write permission - and I just gave the bot admin rights to see if this sorts out the issue.

**Comment by FKLC** [comment] 2020-12-11 22:28
How do you close the bot? Do you exit by pressing CTRL+C? If there is no `chats.json` there is definitely something wrong. Are you using a Windows machine, then it is probably not about file permissions. When the session times out, the bot just doesn't abruptly shuts down. There is probably another problem. Try running it through CMD. Open up a CMD window in that folder and enter WA2DC.exe. When it, for some reason, stops working send the output here and I'll try to understand what's wrong.

**Comment by teejavus** [comment] 2020-12-12 19:29
I was exiting by shutting pc, or just hitting the X on the exe's command window. tried running it through CMD and haven't have any time out. Also closing it with ctrl+c seems to update the chat.json for me.

**Comment by FKLC** [comment] 2020-12-12 19:46
So, is it working now? if so feel free to close the issue.

**Comment by teejavus** [comment] 2020-12-13 07:41
@FKLC finally got the timed out error you wanted

```error processing data: received invalid data
keepAlive failed: connection timed out
panic: couldn't dial whatsapp web websocket: dial tcp: lookup web.whatsapp.com: no such host

goroutine 3230 [running]:
main.initializeWhatsApp()
        command-line-arguments/WA2DC.go:309 +0x254
main.waHandler.HandleError(0x1334a60, 0xc0031de010)
        command-line-arguments/WA2DC.go:390 +0x65
created by github.com/Rhymen/go-whatsapp.(*Conn).handleWithCustomHandlers
        github.com/Rhymen/go-whatsapp@v0.1.0/handler.go:183 +0x16c```

**Comment by teejavus** [comment] 2020-12-13 09:32
One more 

```2020/12/13 14:30:56 [DG0] wsapi.go:82:Open() error connecting to gateway wss://gateway.discord.gg/?v=6&encoding=json, dial tcp 192.168.31.1:443: connectex: No connection could be made because the target machine actively refused it.
2020/12/13 14:30:56 [DG0] wsapi.go:835:reconnect() error reconnecting to gateway, dial tcp 192.168.31.1:443: connectex: No connection could be made because the target machine actively refused it.
keepAlive failed: connection timed out
panic: couldn't dial whatsapp web websocket: dial tcp 192.168.31.1:443: connectex: No connection could be made because the target machine actively refused it.

goroutine 2229 [running]:
main.initializeWhatsApp()
        command-line-arguments/WA2DC.go:309 +0x254
main.waHandler.HandleError(0x1334a60, 0xc002f303b0)
        command-line-arguments/WA2DC.go:390 +0x65
created by github.com/Rhymen/go-whatsapp.(*Conn).handleWithCustomHandlers
        github.com/Rhymen/go-whatsapp@v0.1.0/handler.go:183 +0x16c```

**Comment by seffs** [comment] 2020-12-14 14:15
Are you behind a firewall or in a closed network environment? That looks like a network issue

**Comment by FKLC** [comment] 2020-12-14 17:26
> Are you behind a firewall or in a closed network environment? That looks like a network issue

I second this. Why would there be a local connection problem? I don't think this bug is related to this script.

**Comment by FKLC** [comment] 2020-12-23 15:39
Closing issue because of inactivity. Feel free to open back.

**Closed by FKLC** 2020-12-23 15:39 UTC
