### ISSUE TITLE
A few Bugs (Messages Sending statuses)

### ISSUE THREAD

**Issue by agamsol** [FKLC/WhatsAppToDiscord#49] opened 2021-08-16 19:08 UTC
So i downloaded this and it works amazing man!!! thank you so much for this project
i notice a few bugs that i will be really happy if you fix 

- Attachments are not being sent as files/images
(when you send it from discord the user on whatsapp will see the link for the file/image)

- Whatsapp & Discord Stickers are not being sent (depends on the client side)
sending from whatsapp to discord: Not sending at all
sending from discord to whatsapp: Shows Empty message

**Comment by FKLC** [comment] 2021-11-07 05:45
> Attachments are not being sent as files/images

This is actually by design. I didn't really want the bot to download and then upload a file that can be accessed by URL. The reason files sent from Whatsapp are uploaded as files to Discord is Whatsapp encrypts files and you can't access them without decrypting. 

> Whatsapp & Discord Stickers are not being sent

The latest version supports stickers sent from WhatsApp. I will look into Discord to WhatsApp.

Closing this issue for now.

**Closed by FKLC** 2021-11-07 05:45 UTC
