### ISSUE TITLE
couldn't link device error

### ISSUE THREAD

**Issue by MenachemMarozov** [FKLC/WhatsAppToDiscord#70] opened 2022-03-22 22:34 UTC
whatsapp is not scanning the qr code that the bot is sending in control room, it works on web.whatsapp.com but for some reason on discord its not scanning, ive tried on multiple devices

im getting 2 errors

sometimes it says "please scan again" and other times it says  "couldn't link device"

**Comment by spookycookie27** [comment] 2022-04-29 21:44
try enabling multi device on your whatsapp on your phone before scanning the code?

**Comment by MenachemMarozov** [comment] 2022-05-04 22:57
What's app multi device works, I'm not sure why its not working with WA2DC

I'm using Whatsapp Plus, though it should not make any difference

**Comment by FKLC** [comment] 2022-05-07 22:17
As you are the only person reporting this, I assume the issue is with WhatsApp Plus. Maybe see if the latest version works, but other than that I can't help you. Closing the issue now as it isn't a solvable issue.

**Closed by FKLC** 2022-05-07 22:17 UTC
