### ISSUE TITLE
After accepting the bot to your server: Timed out. Please rescan QR Code. qr code scan timed out

### ISSUE THREAD

**Issue by AshhadS** [FKLC/WhatsAppToDiscord#17] opened 2020-10-17 21:12 UTC
After following all 9 steps as mentioned in the Setup section I get this message continuously even after scanning the QR code i still keep getting this. happy to provide further information if that would help you debug this.

![Screenshot (306)](https://user-images.githubusercontent.com/12772822/96353685-065cbf80-10ec-11eb-94bb-2acdc7c8fd2d.png)

**Comment by FKLC** [comment] 2020-10-17 22:04
I tried to reproduce this error, and what I've found is sometimes WhatsApp scans old QR codes even though they expired. Maybe try to hold the camera closer to the QR code or delete old QR codes to create a clear zone. However this happened after repeating 4 times, so it was hard to reproduce and I'm unsure if it is the cause of it. If that wasn't the case I don't know the reason.

**Comment by AshhadS** [comment] 2020-10-18 11:16
I’ll try that thanks the problem is I keep getting new QR codes so before every minute so before I scan it I’ve got a new QR code. Will it help if I stop the server and scan the QR code

**Comment by VanshDeshwal** [comment] 2020-10-18 11:27
whatsapp scanned the old qr code and shows whatsappweb active and the bot said rescan
buts not generating new qr codes

**Comment by FKLC** [comment] 2020-10-18 13:25
@AshhadS No stopping server will not work.

**Comment by FKLC** [comment] 2020-10-18 13:26
@VanshDeshwal Did it say connection successful as well, it might be just lag. Or you can stop the bot and see if there is a file called `session.json`

**Comment by AshhadS** [comment] 2020-10-18 16:32
@FKLC yay! got it working 🎉  I was scanning the QR code from the discord app from your conversation I realized I should be scanning it from the WhatsApp mobile app. 

I think will be better if you update the Readme with a note or another step saying;
- Go to the newly created Discord server and in the control-room chat you should see a QR code
- Open your Whatsapp Mobile App And scan the QR Code in the Discord server: control-room chat
Then you should see the  message "WhatsApp connection successfully made!" on the Discord server: control-room chat
Great work on this happy to contribute if there is anything more!

Keeping this open till @VanshDeshwal 's issue is resolved can if that is also fixed

**Comment by VanshDeshwal** [comment] 2020-10-18 18:57
> @VanshDeshwal Did it say connection successful as well, it might be just lag. Or you can stop the bot and see if there is a file called `session.json`

no, it didn't say connection successful

**Comment by FKLC** [comment] 2020-10-18 19:42
I genuinely don't know the reason since I cannot reproduce the bug.

**Comment by FKLC** [comment] 2020-10-18 20:26
Let me know if you find a solution but as I've said I cannot help you with that so for now I'm closing this issue

**Closed by FKLC** 2020-10-18 20:26 UTC
