### ISSUE TITLE
The bot crashes abruptly

### ISSUE THREAD

**Issue by MrCrahb** [FKLC/WhatsAppToDiscord#30] opened 2021-04-21 11:07 UTC
exactly as the title mentioned,
i use my own laptop to keep the bot running (ofc using the exe that you compiled)
when i leave my laptop for a while, suddenly i see that the program itself is gone, and i have to reopen it again
any tips / suggestions ?

**Comment by FKLC** [comment] 2021-04-25 01:24
Hi, I still don't know the reason why the bot crashes on some people. I cannot reproduce the bug on my end even though I keep it open for long periods. I made a new release that logs each function that can return an error. I hope that this release will help me understand what is wrong. For now, temporarily, I added another file to the repository. If you download the new version and [this batch file](https://github.com/FKLC/WhatsAppToDiscord/releases/download/v0.3.3/start.bat) and run it using the `start.bat` file, it should restart whenever it crashes. If you notice any crash (you should expect to see `Bot is now running. Press CTRL-C to exit.` more than once), please send what you see on that same window and upload your `logs.txt` (log file doesn't contain any information related to you, if you still have privacy concerns you may redact that part or email to me), so that I can fix the issue. Thanks for your cooperation.

**Comment by MrCrahb** [comment] 2021-04-27 09:20
[logs.txt](https://github.com/FKLC/WhatsAppToDiscord/files/6383396/logs.txt)
sorry i forgot to screenshot

> Hi, I still don't know the reason why the bot crashes on some people. I cannot reproduce the bug on my end even though I keep it open for long periods. I made a new release that logs each function that can return an error. I hope that this release will help me understand what is wrong. For now, temporarily, I added another file to the repository. If you download the new version and [this batch file](https://github.com/FKLC/WhatsAppToDiscord/releases/download/v0.3.3/start.bat) and run it using the `start.bat` file, it should restart whenever it crashes. If you notice any crash (you should expect to see `Bot is now running. Press CTRL-C to exit.` more than once), please send what you see on that same window and upload your `logs.txt` (log file doesn't contain any information related to you, if you still have privacy concerns you may redact that part or email to me), so that I can fix the issue. Thanks for your cooperation.

**Comment by FKLC** [comment] 2021-04-27 12:07
@MrCrahb I deleted your comment becuase it contained private info. I missed that there could be webhook tokens on the log, I'm so sorry. It is not a big deal though. They can't read through it, they can only use it to send messages. If you feel uncomfortable, you can delete the chat that got leaked(ID of the leaked channel: 836526729538830346), it will also remove the webhook, but again, if you don't notice anything then it means probably noone copied.(by the size of the project, probably noone has seen it)

**Comment by FKLC** [comment] 2021-04-27 15:40
So, the issues I found are:
- `2021/04/27 16:56:42 WA2DC.go:710: HTTP 413 Request Entity Too Large, {"message": "Request entity too large", "code": 40005}`: Bot tries to upload a file larger than 8MB. I don't understand why but the upload limit changes constantly by Discord. The bot now won't crash and notify the user.
- `2021/04/27 17:04:04 WA2DC.go:710: Post "https://discord.com/api/v6/webhooks/836526729538830346/[REDACTED]?wait=true": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`: Bot times out while trying to send a message. Now the bot won't crash on timeouts and will try to resend.
- `2021/04/27 17:04:12 WA2DC.go:643: Update check failed. Error: Get "https://api.github.com/repos/FKLC/WhatsAppToDiscord/releases/latest": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`: Bot would crash because the bot doesn't stop if it fails update check and on [line 645](https://github.com/FKLC/WhatsAppToDiscord/blob/0f4c2bb48fbced04d003be5f0fdab9c86afc1877/WA2DC.go#L645) it tries to access `.Body` on `r` even though it is `nil`. So, I fixed that too.

Thanks for sending your log file, so that I could improve the bot. Closing the issue for now. Feel free to reopen if you come across another issue.

**Closed by FKLC** 2021-04-27 15:40 UTC
Labels: bug

**Comment by MrCrahb** [comment] 2021-04-27 15:48
Thx.
